export const ratinho = [
  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/jesus.mp3?raw=true',
    color: '#cc6699',
    name: 'JESUS',
    keycode: 'KeyQ',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/rapaz.mp3?raw=true',
    color: '#cc6699',
    name: 'RAPAZ',
    keycode: 'KeyW',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/uepa.mp3?raw=true',
    color: '#cc6699',
    name: 'UEPAAAA',
    keycode: 'KeyE',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/ratinho.mp3?raw=true',
    color: '#cc6699',
    name: 'RATINHO',
    keycode: 'KeyR',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/pare.mp3?raw=true',
    color: '#cc6699',
    name: 'PARE',
    keycode: 'KeyT',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/vixi.mp3?raw=true',
    color: '#cc6699',
    name: 'VIXI',
    keycode: 'KeyY',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
]