export const ratinho = [
  {
    source: '/virtual-launchpad/audio/jesus.mp3',
    color: '#ffda29',
    name: 'JESUS',
    keycode: 'KeyQ',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: '/virtual-launchpad/audio/rapaz.mp3',
    color: '#ffda29',
    name: 'RAPAZ',
    keycode: 'KeyW',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: '/virtual-launchpad/audio/uepa.mp3',
    color: '#ffda29',
    name: 'UEPAAAA',
    keycode: 'KeyE',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: '/virtual-launchpad/audio/ratinho.mp3',
    color: '#ffda29',
    name: 'RATINHO',
    keycode: 'KeyR',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: '/virtual-launchpad/audio/pare.mp3',
    color: '#ffda29',
    name: 'PARE',
    keycode: 'KeyT',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: '/virtual-launchpad/audio/vixi.mp3',
    color: '#ffda29',
    name: 'VIXI',
    keycode: 'KeyY',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: '/virtual-launchpad/audio/irra.mp3',
    color: '#ffda29',
    name: 'IRRAAAA',
    keycode: 'KeyU',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },

  {
    source: '/virtual-launchpad/audio/queisso.mp3',
    color: '#ffda29',
    name: 'QUE ISSO',
    keycode: 'KeyI',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },

  {
    source: '/virtual-launchpad/audio/cavalo.mp3',
    color: '#ffda29',
    name: 'CAVALO',
    keycode: 'KeyO',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: '/virtual-launchpad/audio/danca.mp3',
    color: '#ffda29',
    name: 'DANÇA GATINHO',
    keycode: 'KeyP',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },

  {
    source: '/virtual-launchpad/audio/fail.mp3',
    color: '#ffda29',
    name: 'FAIL',
    keycode: 'KeyA',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },

  {
    source: '/virtual-launchpad/audio/risada.mp3',
    color: '#ffda29',
    name: 'RISADA',
    keycode: 'KeyS',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },

  {
    source: '/virtual-launchpad/audio/cartoon.mp3',
    color: '#ffda29',
    name: 'CARTOON',
    keycode: 'KeyD',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: '/virtual-launchpad/audio/yamete.mp3',
    color: '#ffda29',
    name: 'YAMETE',
    keycode: 'KeyF',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: '/virtual-launchpad/audio/vinheta.mp3',
    color: '#ffda29',
    name: 'BGM COMERCIAL',
    keycode: 'KeyZ',
    playing: false,
    loaded: false,
    loop: true,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: '/virtual-launchpad/audio/bgm2.mp3',
    color: '#ffda29',
    name: 'BGM CHAVES',
    keycode: 'KeyX',
    playing: false,
    loaded: false,
    loop: true,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: '/virtual-launchpad/audio/bgm3.mp3',
    color: '#ffda29',
    name: 'BGM BOA NOITE',
    keycode: 'KeyC',
    playing: false,
    loaded: false,
    loop: true,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: '/virtual-launchpad/audio/bgm4.mp3',
    color: '#ffda29',
    name: 'BGM PEGADINHA',
    keycode: 'KeyV',
    playing: false,
    loaded: false,
    loop: true,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
]