export const ratinho = [
  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/jesus.mp3?raw=true',
    color: '#cc6699',
    name: 'JESUS',
    keycode: 'KeyQ',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/rapaz.mp3?raw=true',
    color: '#cc6699',
    name: 'RAPAZ',
    keycode: 'KeyW',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/uepa.mp3?raw=true',
    color: '#cc6699',
    name: 'UEPAAAA',
    keycode: 'KeyE',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/ratinho.mp3?raw=true',
    color: '#cc6699',
    name: 'RATINHO',
    keycode: 'KeyR',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/pare.mp3?raw=true',
    color: '#cc6699',
    name: 'PARE',
    keycode: 'KeyT',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/vixi.mp3?raw=true',
    color: '#cc6699',
    name: 'VIXI',
    keycode: 'KeyY',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/irra.mp3?raw=true',
    color: '#cc6699',
    name: 'IRRAAAA',
    keycode: 'KeyU',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },

  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/queisso.mp3?raw=true',
    color: '#cc6699',
    name: 'QUE ISSO',
    keycode: 'KeyI',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },

  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/cavalo.mp3?raw=true',
    color: '#cc6699',
    name: 'CAVALO',
    keycode: 'KeyO',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/danca.mp3?raw=true',
    color: '#cc6699',
    name: 'DANÇA GATINHO',
    keycode: 'KeyP',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },

  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/fail.mp3?raw=true',
    color: '#cc6699',
    name: 'FAIL',
    keycode: 'KeyA',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },

  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/risada.mp3?raw=true',
    color: '#cc6699',
    name: 'RISADA',
    keycode: 'KeyS',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },

  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/cartoon.mp3?raw=true',
    color: '#cc6699',
    name: 'CARTOON',
    keycode: 'KeyD',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/yamete.mp3?raw=true',
    color: '#cc6699',
    name: 'YAMETE',
    keycode: 'KeyF',
    playing: false,
    loaded: false,
    loop: false,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/vinheta.mp3?raw=true',
    color: '#cc6699',
    name: 'BGM COMERCIAL',
    keycode: 'KeyZ',
    playing: false,
    loaded: false,
    loop: true,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/bgm2.mp3?raw=true',
    color: '#cc6699',
    name: 'BGM CHAVES',
    keycode: 'KeyX',
    playing: false,
    loaded: false,
    loop: true,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/bgm3.mp3?raw=true',
    color: '#cc6699',
    name: 'BGM BOA NOITE',
    keycode: 'KeyC',
    playing: false,
    loaded: false,
    loop: true,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
  {
    source: 'https://github.com/leodhb/instant-ratinho/blob/main/audio/bgm4.mp3?raw=true',
    color: '#cc6699',
    name: 'BGM PEGADINHA',
    keycode: 'KeyV',
    playing: false,
    loaded: false,
    loop: true,
    mute: false,
    volume: 0.5,
    seek: 0.0,
    isSeeking: false
  },
]